AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - "spec/**/*"
