name: Ruby

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ruby_version: "3.4.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true

  build:
    needs: setup
    runs-on: ubuntu-latest
    name: Build & Test Ruby

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Ruby from setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Ruby from setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true

      - name: Build gem
        run: gem build crypto_tracker.gemspec

      - name: Publish on RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          VERSION=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' lib/crypto_tracker/version.rb | head -1)
          gem push crypto_tracker-$VERSION.gem
